/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Status */
        get: operations["model_status_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Model Key
         * @description Save a pasted key to the user's .env and apply it, so first-run setup never opens a file.
         */
        post: operations["set_model_key_model_key_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Model Check */
        post: operations["model_check_model_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Rename Project */
        patch: operations["rename_project_projects__project_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Chat */
        get: operations["read_chat_projects__project_id__chat_get"];
        put?: never;
        /** Send Message */
        post: operations["send_message_projects__project_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Context */
        get: operations["list_context_projects__project_id__context_get"];
        put?: never;
        /**
         * Add Paths
         * @description Folders and files by path, all of them or none — a refusal partway through would leave
         *     some attached and an error that says nothing about which.
         */
        post: operations["add_paths_projects__project_id__context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/context/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Files
         * @description Kept before the job starts, so the list shows them while the indexing runs — all of them or
         *     none, the same invariant `add_paths` holds.
         */
        post: operations["add_files_projects__project_id__context_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/context/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Context
         * @description The resource, its copy, its index, and the deck it produced. Removed means removed.
         */
        delete: operations["remove_context_projects__project_id__context__resource_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Deck */
        get: operations["read_deck_projects__project_id__deck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/deck/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Selection */
        put: operations["edit_selection_projects__project_id__deck_selection_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/deck/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Deck */
        get: operations["download_deck_projects__project_id__deck_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Job */
        get: operations["read_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_add_files_projects__project_id__context_files_post */
        Body_add_files_projects__project_id__context_files_post: {
            /** Files */
            files: string[];
        };
        /** Candidate */
        Candidate: {
            /** Id */
            id: string;
            /**
             * Paths
             * @default []
             */
            paths: string[];
            /**
             * Commits
             * @default []
             */
            commits: string[];
        };
        /**
         * ChatMessage
         * @description A `command` entry is what a round actually did - the same outcome line `results` carries
         *     within a turn, persisted so the next turn has it too. Never written by a client; `ChatSend`
         *     covers what a person may put in the log.
         */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "command";
            /** Content */
            content: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * ChatSend
         * @description What a client may put in the log. Only the person's own words — never a reply.
         */
        ChatSend: {
            /** Content */
            content: string;
        };
        /**
         * ContextAdd
         * @description Paths on this machine — folders, files, or a mix of both.
         */
        ContextAdd: {
            /** Locations */
            locations: string[];
        };
        /** Deck */
        Deck: {
            selection: components["schemas"]["Selection"];
            /**
             * @default {
             *       "theme": "technical",
             *       "heading_font": "Aptos Display",
             *       "body_font": "Aptos"
             *     }
             */
            design: components["schemas"]["DeckDesign"];
            /** Slides */
            slides?: components["schemas"]["Slide"][] | null;
        };
        /**
         * DeckDesign
         * @description Deck-level art direction. Layout remains semantic; code owns the pixel geometry.
         */
        DeckDesign: {
            /**
             * Theme
             * @default technical
             * @enum {string}
             */
            theme: "technical" | "light" | "dark" | "editorial" | "bold";
            /** Accent */
            accent?: string | null;
            /**
             * Heading Font
             * @default Aptos Display
             */
            heading_font: string;
            /**
             * Body Font
             * @default Aptos
             */
            body_font: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /**
             * State
             * @enum {string}
             */
            state: "running" | "done" | "failed";
            /** Step */
            step: string;
            /** Detail */
            detail?: string | null;
        };
        /** ModelCheck */
        ModelCheck: {
            /** Ok */
            ok: boolean;
            /** Reply */
            reply: string;
        };
        /** ModelKey */
        ModelKey: {
            /** Api Key */
            api_key: string;
        };
        /** ModelStatus */
        ModelStatus: {
            /** Provider */
            provider: string | null;
            /** Model */
            model: string;
            /** Configured */
            configured: boolean;
            /** Via Gateway */
            via_gateway: boolean;
            /** Models */
            models: string[];
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Resources
             * @default []
             */
            resources: components["schemas"]["Resource"][];
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
        };
        /** ProjectRename */
        ProjectRename: {
            /** Name */
            name: string;
        };
        /** Resource */
        Resource: {
            /** Id */
            id: string;
            kind: components["schemas"]["ResourceKind"];
            /** Name */
            name: string;
            /** Location */
            location: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /**
         * ResourceKind
         * @enum {string}
         */
        ResourceKind: "folder" | "file";
        /**
         * Scope
         * @description What the request puts in play — the one model output that precedes any derived work.
         */
        Scope: {
            /** Since */
            since?: string | null;
            /** Until */
            until?: string | null;
            /**
             * Paths
             * @default []
             */
            paths: string[];
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /** Audience */
            audience?: string | null;
            /** Slide Budget */
            slide_budget: number;
        };
        /** Scored */
        Scored: {
            candidate: components["schemas"]["Candidate"];
            /**
             * Signals
             * @default {}
             */
            signals: {
                [key: string]: number;
            };
            /** Score */
            score: number;
            /** Reason */
            reason?: string | null;
        };
        /**
         * Selection
         * @description What the deck will say and why — visible and editable before anything renders.
         */
        Selection: {
            /** Request */
            request: string;
            scope: components["schemas"]["Scope"];
            /**
             * Chosen
             * @default []
             */
            chosen: components["schemas"]["Scored"][];
            /**
             * Cut
             * @default []
             */
            cut: components["schemas"]["Scored"][];
        };
        /** SelectionEdit */
        SelectionEdit: {
            /** Keep */
            keep: string[];
        };
        /** Slide */
        Slide: {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Free
             * @default false
             */
            free: boolean;
            /** Title */
            title: string;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /**
             * Bullets
             * @default []
             */
            bullets: string[];
            /**
             * Secondary Title
             * @default
             */
            secondary_title: string;
            /**
             * Secondary Bullets
             * @default []
             */
            secondary_bullets: string[];
            /** Image */
            image?: string | null;
            /**
             * Layout
             * @default auto
             * @enum {string}
             */
            layout: "auto" | "cover" | "section" | "content" | "two_column" | "statement" | "image";
            /**
             * Speaker Notes
             * @default
             */
            speaker_notes: string;
            /**
             * Elements
             * @default []
             */
            elements: components["schemas"]["VisualElement"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VisualElement
         * @description One editable layer on a normalized 100×100 slide canvas.
         */
        VisualElement: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "shape" | "line" | "image";
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Text
             * @default
             */
            text: string;
            /** Image */
            image?: string | null;
            /**
             * Shape
             * @default rectangle
             * @enum {string}
             */
            shape: "rectangle" | "rounded" | "ellipse" | "triangle" | "chevron";
            /**
             * Fill
             * @default transparent
             */
            fill: string;
            /**
             * Stroke
             * @default transparent
             */
            stroke: string;
            /**
             * Stroke Width
             * @default 0
             */
            stroke_width: number;
            /**
             * Color
             * @default text
             */
            color: string;
            /**
             * Font Size
             * @default 20
             */
            font_size: number;
            /**
             * Font Weight
             * @default regular
             * @enum {string}
             */
            font_weight: "regular" | "semibold" | "bold";
            /** Font Family */
            font_family?: string | null;
            /**
             * Align
             * @default left
             * @enum {string}
             */
            align: "left" | "center" | "right";
            /**
             * Valign
             * @default top
             * @enum {string}
             */
            valign: "top" | "middle" | "bottom";
            /**
             * Rotation
             * @default 0
             */
            rotation: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    model_status_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatus"];
                };
            };
        };
    };
    set_model_key_model_key_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelKey"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_check_model_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCheck"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_project_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_chat_projects__project_id__chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_projects__project_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSend"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_context_projects__project_id__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_paths_projects__project_id__context_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_files_projects__project_id__context_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_files_projects__project_id__context_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_context_projects__project_id__context__resource_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_deck_projects__project_id__deck_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_selection_projects__project_id__deck_selection_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectionEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_deck_projects__project_id__deck_file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
